# Configuration for advanced action recognition model
name = "advanced_action_recognition"

[dataset]
processed_data = "data/processed/mmr_act/data_advanced.pkl"
seed = 42
train_split = 0.8
val_split = 0.1
test_split = 0.1
stacks = 10
zero_padding = "per_data_point"
max_points = 22
forced_rewrite = false
cross_validation = "5-fold"
num_folds = 5
fold_number = 0
raw_data_path = "data/raw_carelab"

[model]
name = "attdgcnn"  # Choose from: "attdgcnn", "hybrid", "ensemble"
k = 30
aggr = "max"

# Optional parameters for ensemble model
# model_types = ["dgcnn", "attdgcnn", "hybrid"]
# weights = [0.3, 0.4, 0.3]  # Relative importance of each model in ensemble

[train]
optimizer = "adamw"
learning_rate = 0.001
weight_decay = 0.0001
batch_size = 32
num_workers = 4
epochs = 300

[advanced]
use_mixup = true
label_smoothing = 0.1
focal_loss = true
scheduler = "cosine_warmup"
early_stopping = 15
precision = 16
merge_classes = true