# Configuration for hybrid model architecture
name = "hybrid_point_cloud_model"

[dataset]
processed_data = "data/processed/mmr_act/data_hybrid.pkl"
seed = 42
train_split = 0.8
val_split = 0.1
test_split = 0.1
stacks = 15
zero_padding = "per_data_point"
max_points = 22
forced_rewrite = false
cross_validation = "5-fold"
num_folds = 5
fold_number = 0
raw_data_path = "data/raw_carelab"

[model]
name = "hybrid"
k = 30
aggr = "max"

[train]
optimizer = "adamw"
learning_rate = 0.001
weight_decay = 0.0001
batch_size = 32
num_workers = 4
epochs = 300

[advanced]
use_mixup = true
label_smoothing = 0.1
focal_loss = true
scheduler = "one_cycle"
early_stopping = 15
precision = 16
merge_classes = true