seed = 20
raw_data_path = 'data/raw_carelab'
processed_data = '/cluster/projects/kite/koorosh/Data/MiliPointCareLab/data/processed_carelab/mmr_action/seed_20_stacks_20_padd_point_task_action.pkl'
cross_validation = '5-fold'
num_folds = 5
fold_number = 1
train_split = 0.8
val_split = 0.1
test_split = 0.1
stacks = 20
zero_padding = 'per_data_point'
